name: site-monitor

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75.0
        target: ${{matrix.os == 'windows-latest' && 'x86_64-pc-windows-gnu' || 'x86_64-unknown-linux-gnu' }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload Linux executable
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: site-monitor-linux
        path: |
          target/release/site-monitor
          target/release/config.json
          target/release/websites.txt

    - name: Upload Windows executable
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: site-monitor-windows
        path: |
          target/release/site-monitor.exe
          target/release/config.json
          target/release/websites.txt

    - name: Upload macOS executable
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: site-monitor-macos
        path: |
          target/release/site-monitor
          target/release/config.json
          target/release/websites.txt
